### PR TITLE
[WIP] First version of mainhall theme component

### PR DESCRIPTION
**Pull request by sodoku**
Component to set the lights of the mainhall to a certain theme. Might be replaced by leting Farbgeber do this.

### CODE REVIEW

**Comment by bergie** [comment]
Git history needs a cleanup

**Comment by sodoku** [comment]
@bergie cleaned the git history and added some fixes. The test still times out though. Can you see any obvious mistakes in the test?

**Comment by bergie** [comment]
I'll check later today. You can also see a lot more by setting `DEBUG=fbp-spec:*`

**Comment by bergie** [comment]
Updated implementation of this idea in #110

**Pull request closed without merging**
